[{"created_at":"2011-01-31 14:40:30", "updated_at":"2014-02-12 18:02:56", "name":"Ben", "body":"Attached is a photo of one of your tents, at our place in the mountains of S.W. France. We had about 20 adults (all family) staying in the house,and our combined children (9) in your tent! They loved it - the tent was cool during the heat of the day, and warm enough during the mountain nights... thanks!", "enabled":0},
 {"created_at":"2011-03-17 16:39:27", "updated_at":"2012-02-05 14:29:41", "name":"Jon", "body":"Just wanted to let you know that we absolutely LOVE the SoulPad! It was minus 3 degrees on New Years Eve and we all sat in the tent in t-shirts, toasty warm with the blaze stove! It was brilliant - all our friends want one, and we're now looking forward to a year of excellent camping and festival fun! Thank you and Happy New Year!", "enabled":0},
 {"created_at":"2011-03-17 16:40:09", "updated_at":"2011-03-17 16:40:09", "name":"Ray", "body":"Dudes - One SoulPad received this afternoon. Wickedness! Thanks for getting it to me it was very fast delivery across the open seas. Now I have something to write home about, and be the envy of the festival crowds. Thanks again", "enabled":0},
 {"created_at":"2011-03-17 16:40:22", "updated_at":"2011-12-13 21:19:50", "name":"Mark", "body":"Thank you so much for helping My Dear Lady Wife, Lucy get me a wondrous SoulPad. I put it up in the garden literally minutes after unwrapping it. One of the best Birthday presents ever! Even at 43! As a family, we look forward to taking our SoulPad to all sorts of different destinations. Once again thank you for Kind attention and efficient service.", "enabled":0},
 {"created_at":"2011-03-17 16:40:35", "updated_at":"2011-03-17 16:40:35", "name":"Bob", "body":"The Tribe arrived today - fantastic service. We had it up in 15 minutes - it is huge, beyond our imagination! And it has a sewn in groundsheet which we had not picked up from blurb - excellent. Everyone is now very enthusiastic about going camping again this year - although it is going to be the maddest tent on most of the sites we go to! And to think we nearly bought a tentipi for three times as much!!!!", "enabled":0},
 {"created_at":"2011-03-17 16:40:49", "updated_at":"2011-03-17 16:40:49", "name":"Jo", "body":"We just tried out our shiny new SoulPad 5000-lite on the weekend. It was so easy to put up and take down, and we were able to have friends come and join us and chill out in it as it was so cosy and spacious. It looked brilliant with big cushions and furry blankets, but the next thing on the list is some carpet and sheepskin for the final touches. I was just writing to say thank you for putting the fun back into camping...its going to be used again next weekend!", "enabled":0},
 {"created_at":"2011-03-17 16:41:22", "updated_at":"2011-03-17 16:41:22", "name":"Colin", "body":"I just wanted to let you know that I received the tent today. Wow! 3 days from ordering it to it arriving at my front door - that was really fast! I can't wait to put it up. I'm going to e using it at the southern lights festival as I wanted something unique!! At least I will be able to find my tent in amongst the sea of horrible coloured plastic tents!", "enabled":0},
 {"created_at":"2011-03-17 16:41:34", "updated_at":"2011-03-17 16:41:34", "name":"Matthew", "body":"The SoulPad is great. We used it as our Medi tent at a tournament. Perfect! Very versatile too. Will use it on school camping trips etc as well as for family use! You did a fantastic job - thank you so much. I will sing the praises of SoulPad to all my Headmaster friends and encourage them to buy one for their schools!", "enabled":0},
 {"created_at":"2011-03-17 16:41:49", "updated_at":"2011-03-17 16:41:49", "name":"Tonya", "body":"Thank you so much for sorting me out! Got our tent on Friday and put it up at weekend. It is beautiful. We are all very happy and even husband approves! Going to try it out in Dorset in 3 weeks time and can't wait. Like you said, it was sooooo easy to put up and is just such a lovely relaxing place to be in (except when kids are running around it in circles screaming with excitement!).", "enabled":0},
 {"created_at":"2011-03-17 16:42:01", "updated_at":"2011-03-17 16:42:01", "name":"Jon", "body":"Let me say how pleased I am with both your prompt service, and the quality of the components!", "enabled":0}
].each do |params|
  item = Testimonial.new(params)
  item.enabled = true
  item.save ? "testimonial created: #{item}" : "testimonial error: #{item}"
end
