#!/bin/env ruby
# encoding: utf-8

offers=[
["IP24 2RY","Norfolk", "Peony Floral Design Wedding Bells and Glamping Holidays","10% discount for midweek SoulPadders","https://s3.amazonaws.com/soulpad-affiliates/peony.png" ,"https://www.peonyfloraldesign.co.uk/bell-tents.htm", "Spacious 5 metre Bell Tents are pre-erected and beautifully furnished ready for your arrival at the venue of your choice in Norfolk or Suffolk.", "7758370063"],
["IP24 2RY","Co. Laois, Ireland", "Glamping Under the Stars","10% discount for SoulPadders.","https://s3.amazonaws.com/soulpad-affiliates/glamping_under_stars.png", "http://www.glampingunderthestars.ie/", "Gorgeous glamping at our family-run, boutique glampsite in the heart of the Irish countryside. Stay in our fully-furnished SoulPad bell tents or our quirky horse drawn caravan.","+353 860651485"],
["IP24 2RY","Bristol", "Lulubelltents.co.uk","10% discount for SoulPadders.","https://s3.amazonaws.com/soulpad-affiliates/image6.png", "http://lulubelltents.co.uk/","Our service includes pitching, styling, packing down, cleaning and linen washing, all you do is pick the perfect location.", "07899 763120."],
["IP24 2RY","Wherever You Are", "Glamcamper.co.uk","10% discount for SoulPadders.","https://s3.amazonaws.com/soulpad-affiliates/Glam-camper-bell-twnt-camping-glamping-wedding.png", "http://glamcamper.co.uk/", "Well set up and furnish our tents ready for you and your guests.","07833 615 655"],
["IP24 2RY","Scotland", "Kelburn Castle & Estate","10% discount for SoulPadders.","https://s3.amazonaws.com/soulpad-affiliates/kelburn.png","http://www.kelburnestate.com/","Secluded glamping in the grounds of our 13th Century castle and pre-erected SoulPads too.", "01475 568685"],
["IP24 2RY","Norfolk", "Riddlesworth Park","10% discount for SoulPadders.","https://s3.amazonaws.com/soulpad-affiliates/riddlesworth.png","http://riddlesworthglamping.co.uk/", "Experience the ever-changing landscape in our 800 acres of restored Norfolk parkland and SoulPad's partner campsite.","01953 681254"],
["IP24 2RY","Norfolk", "Whitlingham Broad Campsite","10% discount (excluding public holidays) if you call and mention SoulPad.","https://s3.amazonaws.com/soulpad-affiliates/whitlingham.png","http://www.whitlinghambroadcampsite.com/", "Situated within the Broads National Park surrounded by 80 acres of beautiful Country Park.","07794 401591"],
["IP24 2RY","Norfolk", "The Grove at Cromer","10% discount if you call and mention SoulPad.","https://s3.amazonaws.com/soulpad-affiliates/grove_cromer.png" ,"http://thegrovecromer.co.uk/glamping/","Beautiful SoulPads with woodburning stoves, solar power, and super-comfy beds, all on the grounds of The Grove, Cromer.", "01263 512412"],
["IP24 2RY","Norfolk", "Gorsey Meadow","10% discount on midweek stays for SoulPadders","https://s3.amazonaws.com/soulpad-affiliates/gorseyfarm.png", "http://www.gorseymeadow.co.uk/", "Our wonderfully secluded meadow allows adults to escape the hustle and bustle and children to enjoy space and nature in a safe environment.", "01603 880339"],
["IP24 2RY","Warwick", "Mousley House Farm Camping & Glamping Site","5% discount for SoulPadders with code MOUSE1!","https://s3.amazonaws.com/soulpad-affiliates/mousley.png","http://www.mousleyhousefarmcampsite.co.uk/", "Relax and unwind surrounded by nothing but the gently rolling hills of Warwickshire.","07443 475434"],
["IP24 2RY","Pyrenees, Catalunya", "Forest Days Glamping","10% discount for SoulPadders!","https://s3.amazonaws.com/soulpad-affiliates/forestdays.png","http://www.forestdaysglamping.com/", "Set in the foothills of the Catalan Pyrenees. One fully furnished cotton tent. Five hectares of meadows and unspoilt forest. One wild and authentic experience.", "+34 722 394 264"],
["IP24 2RY","Jijona, Spain", "The Olive Garden Glamping Retreat","10% discount for SoulPadders.","https://s3.amazonaws.com/soulpad-affiliates/olive_garden.png", "http://www.theolivegarden.es", "The Olive Garden is a newly developed glamping retreat in Alicante, Spain. You will arrive to find your luxury bell tent surrounded by 28 olive trees overlooking beautiful mountainous scenery.","+447980 897690"],
["IP24 2RY","N.E. Scotland", "NES Bushcraft","","https://s3.amazonaws.com/soulpad-affiliates/nes_bushcraft.png", "http://nesbushcraft.wix.com/nesbushcraft", "Whether its Bushcraft, primitive skills, wilderness survival or simply camping out, everybody is welcome. Taking part, learning, sharing your knowledge and skills is what it's all about.","07767 986558"],
["IP24 2RY","Suffolk", "Ling's Meadow: Carefree Camping","5% discount when you mention 'SoulPad'.","https://s3.amazonaws.com/soulpad-affiliates/thumb_2013_LingsMeadow_0022.png", "http://lingsmeadow.co.uk/","Ling\’s Meadow is a small, friendly campsite based on our family farm in rural Suffolk. The campsite is very much ‘off grid’.","01359 250594"],
["IP24 2RY","North Norfolk", "2posh2pitch Luxury Bell Tent Hire","10% discount when you mention 'SoulPad'.","https://s3.amazonaws.com/soulpad-affiliates/2posh2pitch.png", "http://www.2posh2pitch.co.uk/","2posh2pitch is a local family run business in Brancaster Staithe, which is situated along the beautiful North Norfolk Coastline.","07879 773382"],
["IP24 2RY","Norfolk", "Amber's Bell Tent Camping","£10 off per night when you mention 'SoulPad'.","https://s3.amazonaws.com/soulpad-affiliates/ambersbelltents.png", "http://www.ambersbelltents.co.uk", "Amber's Bell Tent Camping, Mannington Hall, Norfolk is set in the grounds of a spectacular medieval hall. A truly outstanding setting.","07580 072 861"],
["IP24 2RY","Snowdonia", "Llechrwd Riverside Campsite","Visitors should mention 'SoulPad' for a 5% discount.","https://s3.amazonaws.com/soulpad-affiliates/1369425874.jpg", "http://www.llechrwd.co.uk/", "A small, friendly, family run campsite in beautiful Snowdonia. Please come and try a stay in our furnished Bell tent, camping is easy in a ready set up tent, just turn up, put the kettle on and relax.","01766 590240"],
["IP24 2RY","Dorset", "Green Valley Yurts","Visitors should mention 'SoulPad' for a 10% discount.","https://s3.amazonaws.com/soulpad-affiliates/greenvalleyyurts.png", "http://www.greenvalleyyurts.com/", "Green Valley Yurts is set on an organic farm nestled deep in the heart of the beautiful Cerne Valley in Dorset.", "07970 298427"],
["IP24 2RY","Portugal", "Senses Camping","Visitors should mention 'SoulPad' for a 10% discount.","https://s3.amazonaws.com/soulpad-affiliates/senses.png", "http://www.sensescamping.com/","Senses Camping is set in the stunning Serra da Estrella nature reserve, this untouched paradise is a place where time stood still.","00351-910488800"],
["IP24 2RY","Suffolk", "Ivy Grange Farm","Visitors should mention 'SoulPad' for a 5% discount.","https://s3.amazonaws.com/soulpad-affiliates/ivy_grange_100.png", "http://www.ivygrangefarm.co.uk/","Recommended by The Guardian - Nick & Kim Hoare are eagerly gearing up to provide tranquil, soulful, SoulPad accommodation in Suffolk.", "07802 456087"],
["IP24 2RY","England", "Schools Under Canvas","Mention SoulPad on booking for a 10% discount.","https://s3.amazonaws.com/soulpad-affiliates/Under-Canvas-logo---SMALL.png", "http://schoolsundercanvas.co.uk","Under Canvas is a modern residential concept for primary schools, offering exclusive school camp experiences. We will bring the tents, the activities and our passion for outdoor learning into your school.","0845 47 47 851"],
["IP24 2RY","Killarney, Ireland", "Grove Lane Glamping","Mention SoulPad on booking to enjoy a 10% discount. This cannot be used in conjunction with any other offers.","https://s3.amazonaws.com/soulpad-affiliates/soulpad_gillarney.png","http://www.killarneyglamping.com", "Grove Lane Glamping is in a region of Ireland's southwest famous for it's unspoiled mountains and lakes.","+353 (0) 87 9750110"],
["IP24 2RY","Isle of Wight", "Wight Bells Camping","SoulPadders will receive a 5% discount.","https://s3.amazonaws.com/soulpad-affiliates/wightbells1_100.png", "http://wightbellscamping.co.uk/","A small family run campsite featured in The Sunday Times.", "+44 (0) 7811 706921"],
["IP24 2RY","Hungary", "Glamping Hungary","SoulPadders welcomed with a homecooked Hungarian goulash dinner with a bottle of wine and a delicious breakfast hamper.","https://s3.amazonaws.com/soulpad-affiliates/glamp_hungary.png","http://www.glampinghungary.co.uk", "No description provided.","003 6306 229357"],
["IP24 2RY","Pembrokeshire", "Not Just Any Tent","Offer a happy 10% discount (not in conjunction with any other offer) to SoulPadders.","https://s3.amazonaws.com/soulpad-affiliates/not_just_any_tent.png", "http://www.notjustanytent.co.uk/", "No description provided.","07813 910705"],
["IP24 2RY","Devon", "Babes in The Woods","Book 12+ places & the bride goes free!","https://s3.amazonaws.com/soulpad-affiliates/babes_2.png","http://www.babesinthewoods.co.uk/","Hen Parties with a difference.","020 7193 8633"],
["IP24 2RY","Sussex", "Woodside","10% discount to those who mention SoulPad.","https://s3.amazonaws.com/soulpad-affiliates/bea.png", "http://www.yurtandbreakfast.co.uk/", "Glamping at Woodside B&B.", "01580 830903"],
["IP24 2RY","Norfolk", "West Lexham","5% discount to those who book 2 nights or more.","https://s3.amazonaws.com/soulpad-affiliates/westlex.jpg", "http://www.westlexham.org/", "Permaculture Residency.", "01760 755434"],
["IP24 2RY","Dorset", "Old Bidlake Farm Camping","There's a free, deluxe breakfast hamper (locally sourced) for anyone mentioning 'SoulPad' when booking.","https://s3.amazonaws.com/soulpad-affiliates/The-Lavvu-Tent.jpg", "http://www.oldbidlake-farm-camping.co.uk/","No description provided.","01938 538080"],
["IP24 2RY","Norfolk and Suffolk", "Go Camping","5% discount which can be used in conjunction with other offers.","https://s3.amazonaws.com/soulpad-affiliates/temp.jpg" ,"Go Camping","http://www.gocampinguk.co.uk", "No description provided.",""],
["IP24 2RY","Nr. Sydney Australia.", "Mojosurf Surf School","10% off the rack rate.","https://s3.amazonaws.com/soulpad-affiliates/surf3_small.jpg", "http://www.mojosurf.com/default.htm","No description provided.",""],
["IP24 2RY","West Cork, Ireland.", "Chleire Haven","10% off for 2/3 people, 20% off for 4/5 people, 25% off for 6 people.","https://s3.amazonaws.com/soulpad-affiliates/capeyurts-005.jpg","http://www.chleire-haven.com/","No description provided.",""],
["IP24 2RY","North Yorkshire", "Kendall Bank Farm","Complimentary breakfast pack for two including Tea, Coffee, Milk, bacon, sausage, eggs and bread. Veggie Option/ Special diet available.","https://s3.amazonaws.com/soulpad-affiliates/SoulPad_by_stream.jpg", "http://kendallbankfarm.com", "No description provided.",""],
["IP24 2RY","Scarborough", "Pinewood Holiday Park","5% discount. Can be used in conjunction with other offers.","https://s3.amazonaws.com/soulpad-affiliates/pinewood.jpg","http://pinewoodpark.co.uk/", "No description provided.",""]
]


offers.each do |postcode, location, title, offer, image, website, description, tel|
  puts title
  a = AffiliateEngine::Engine::Offer.create(title: title, postcode: postcode, website: website, description: description, enabled: 1, contact_tel: tel, contact_email:"enquiries@soulpad.co.uk", offer: offer, location:location, view_by_appt: 1)
  puts image
  a.offer_images.new.upload_from_url(image)
  a.save!
end
